[theme]
base="light"
primaryColor="#f10eed"
backgroundColor="#eff1ea"
secondaryBackgroundColor="#dae2ee"
textColor="#6c708e"


[Database]
mode= "postgresql"
host= "localhost"
port= "5432"
dbname= "postgres"
user= "postgres"
password= "041104"

